avatar: /assets/img/favicons/android-icon-192x192.png
baseurl: ''
collections:
  tabs:
    output: true
    sort_by: order
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
description: Snoqualmie Valley Citizens for Schools, a nonprofit 501(c)(4) organization that promotes public schools in the Snoqualmie Valley.
disqus:
  comments: false  # boolean type, the global switch for posts comments.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - Rakefile
github:
  username: calef
google_analytics:
  id: ''
  pv:
    enabled: false
google_site_verification: google_meta_tag_verification
img_cdn: ''
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
lang: en-US
paginate: 5
permalink: /posts/:title/
repository: Snoqualmie-Valley-Citizens-for-Schools/svcs.crickertech.com
sass:
  style: compressed
social:
  name: Snoqualmie Valley Citizens for Schools
  email: svcitizensforschools@gmail.com
  links:
    - https://twitter.com/snovalleyc4s
    - https://www.facebook.com/SnoqualmieValleyCitizensforSchools
tagline: Promoting public schools in the Snoqualmie Valley
theme: jekyll-theme-chirpy
timezone: America/Los_Angeles
title: Snoqualmie Valley Citizens for Schools
toc: true
twitter:
  username: snovalleyc4s
url: 'https://svcs.crickertech.com'

#TODO below this point

defaults:
  -
    scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true    # Hide title in mobile screens.
