baseurl: ''
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
defaults:
  -
    scope:
      path: ''          # An empty string here means all files in the project
    values:
      layout: post
description: Snoqualmie Valley Citizens for Schools is a nonprofit 501(c)(4) organization that promotes public schools in the Snoqualmie Valley.
exclude:
  - .tm_properties
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Rakefile
  - README.md
google_analytics_ua: 'UA-192044364-1'
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
lang: en-US
paginate: 6
permalink: /posts/:title/
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
repository: Snoqualmie-Valley-Citizens-for-Schools/svcitizensforschools.org
sass:
  style: compressed
social:
  name: Snoqualmie Valley Citizens for Schools
  email: svcitizensforschools@gmail.com
  links:
    - https://twitter.com/snovalleyc4s
    - https://www.facebook.com/SnoqualmieValleyCitizensforSchools
tagline: Promoting public schools in the Snoqualmie Valley
theme: uswds-jekyll
timezone: America/Los_Angeles
title: Snoqualmie Valley Citizens for Schools
twitter:
  username: snovalleyc4s
url: 'https://svcitizensforschools.org'
